import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";
import favoriteFoods from "../data/foods";
import Foods from "../types/foods";
import FoodCard from "../components/FoodCard";
import { ChangeEvent, useEffect, useState } from "react";

interface Props {
  foods: Foods;
}

const Home: NextPage<Props> = ({ foods }) => {
  const [filter, setFilter] = useState<string>("");
  const [filteredFoods, setFilteredFoods] = useState<Foods>(foods);

  const handleOnChange = (event: ChangeEvent<HTMLInputElement>) => {
    const filterText = event.target.value;
    setFilter(filterText);
  };

  useEffect(() => {
    if (filter.length > 0) {
      setFilteredFoods((foods) =>
        foods.filter((food) =>
          food.name.toLowerCase().includes(filter.toLowerCase())
        )
      );
    } else {
      setFilteredFoods(foods);
    }
  }, [filter, foods]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header title="My Favorite Foods" />
      <main className={styles.main}>
        <div>
          <label htmlFor="filter">Filter</label>
          <input
            type="text"
            name="filter"
            id="filter"
            value={filter}
            onChange={handleOnChange}
          />
        </div>
        <div>
          {filteredFoods.map((food) => (
            <FoodCard food={food} key={food._id} />
          ))}
        </div>
      </main>
    </div>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const foods = favoriteFoods;
  return {
    props: {
      foods,
    },
  };
};
